In [1]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Dell\Desktop\data set\creditcard.csv")

In [2]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [3]:
df.shape

(284807, 31)

In [4]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [5]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [6]:
df.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

In [9]:
columns_to_scale = ['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
                    'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
                    'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount']

x = df[columns_to_scale]  # Features to be scaled
y = df['Class']

In [10]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()

# Fit the scaler on the selected columns
ss.fit(x)

StandardScaler()

In [11]:
ss.transform(x)

array([[-1.99658302, -0.69424232, -0.04407492, ...,  0.33089162,
        -0.06378115,  0.24496426],
       [-1.99658302,  0.60849633,  0.16117592, ..., -0.02225568,
         0.04460752, -0.34247454],
       [-1.99656197, -0.69350046, -0.81157783, ..., -0.13713686,
        -0.18102083,  1.16068593],
       ...,
       [ 1.6419735 ,  0.98002374, -0.18243372, ...,  0.01103672,
        -0.0804672 , -0.0818393 ],
       [ 1.6419735 , -0.12275539,  0.32125034, ...,  0.26960398,
         0.31668678, -0.31324853],
       [ 1.64205773, -0.27233093, -0.11489898, ..., -0.00598394,
         0.04134999,  0.51435531]])

In [12]:

df = pd.DataFrame(ss.transform(x), columns=columns_to_scale)

In [13]:
df

Time        V1        V2        V3        V4        V5        V6  \
0      -1.996583 -0.694242 -0.044075  1.672773  0.973366 -0.245117  0.347068   
1      -1.996583  0.608496  0.161176  0.109797  0.316523  0.043483 -0.061820   
2      -1.996562 -0.693500 -0.811578  1.169468  0.268231 -0.364572  1.351454   
3      -1.996562 -0.493325 -0.112169  1.182516 -0.609727 -0.007469  0.936150   
4      -1.996541 -0.591330  0.531541  1.021412  0.284655 -0.295015  0.071999   
...          ...       ...       ...       ...       ...       ...       ...   
284802  1.641931 -6.065842  6.099286 -6.486245 -1.459641 -3.886611 -1.956690   
284803  1.641952 -0.374121 -0.033356  1.342145 -0.521651  0.629040  0.794446   
284804  1.641974  0.980024 -0.182434 -2.143205 -0.393984  1.905833  2.275262   
284805  1.641974 -0.122755  0.321250  0.463320  0.487192 -0.273836  0.468155   
284806  1.642058 -0.272331 -0.114899  0.463866 -0.357570 -0.009089 -0.487602   

              V7        V8        V9  ...       V20       V21       V22  \
0       0.193679  0.082637  0.331128  ...  0.326118 -0.024923  0.382854   
1      -0.063700  0.071253 -0.232494  ... -0.089611 -0.307377 -0.880077   
2       0.639776  0.207373 -1.378675  ...  0.680975  0.337632  1.063358   
3       0.192071  0.316018 -1.262503  ... -0.269855 -0.147443  0.007267   
4       0.479302 -0.226510  0.744326  ...  0.529939 -0.012839  1.100011   
...          ...       ...       ...  ...       ...       ...       ...   
284802 -3.975628  6.116573  1.742559  ...  1.914365  0.290602  0.154146   
284803  0.019667  0.246886  0.532299  ...  0.077330  0.291625  1.273781   
284804 -0.239939  0.593140  0.393630  ...  0.001811  0.315913  0.796788   
284805 -0.554672  0.568631  0.356887  ...  0.165300  0.361112  1.102451   
284806  1.274769 -0.347176  0.442532  ...  0.496739  0.355411  0.886149   

             V23       V24       V25       V26       V27       V28    Amount  
0      -0.176911  0.110507  0.246585 -0.392170  0.330892 -0.063781  0.244964  
1       0.162201 -0.561131  0.320694  0.261069 -0.022256  0.044608 -0.342475  
2       1.456320 -1.138092 -0.628537 -0.288447 -0.137137 -0.181021  1.160686  
3      -0.304777 -1.941027  1.241904 -0.460217  0.155396  0.186189  0.140534  
4      -0.220123  0.233250 -0.395202  1.041611  0.543620  0.651816 -0.073403  
...          ...       ...       ...       ...       ...       ...       ...  
284802  1.624574 -0.841000  2.756320  0.518500  2.337901  2.495529 -0.350151  
284803  0.019958 -1.677920 -1.163726 -0.819647  0.169641 -0.162164 -0.254117  
284804 -0.060053  1.056944  0.509797 -0.181182  0.011037 -0.080467 -0.081839  
284805 -0.261503  0.203428 -1.091855  1.133635  0.269604  0.316687 -0.313249  
284806  0.603365  0.014526 -0.908631 -1.696853 -0.005984  0.041350  0.514355  

[284807 rows x 30 columns]

In [14]:
y

0         0
1         0
2         0
3         0
4         0
         ..
284802    0
284803    0
284804    0
284805    0
284806    0
Name: Class, Length: 284807, dtype: int64

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((227845, 30), (56962, 30), (227845,), (56962,))

In [16]:
from sklearn.linear_model import LogisticRegression

# Train logistic regression
lr = LogisticRegression()
lr.fit(x_train, y_train)

C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [18]:
lr.score(x_test,y_test)*100

99.86482216214318

In [22]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, classification_report

# Predict on the test set
y_pred = lr.predict(x_test)

# Confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Precision and Recall
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")

# Classification Report (includes precision, recall, F1-score)
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Confusion Matrix:
[[56829    35]
 [   42    56]]
Precision: 0.62
Recall: 0.57

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.62      0.57      0.59        98

    accuracy                           1.00     56962
   macro avg       0.81      0.79      0.80     56962
weighted avg       1.00      1.00      1.00     56962



In [23]:
conf_matrix

array([[56829,    35],
       [   42,    56]])

In [24]:
from sklearn.metrics import accuracy_score

# Predict on the test set
y_pred = lr.predict(x_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")


Accuracy: 1.00
